apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    app.kubernetes.io/part-of: kube-sre-gym
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app.kubernetes.io/part-of: kube-sre-gym
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    app.kubernetes.io/part-of: kube-sre-gym
---
apiVersion: v1
kind: Namespace
metadata:
  name: hackathon
  labels:
    app.kubernetes.io/part-of: kube-sre-gym
